# Generated by Django 3.2.7 on 2021-09-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(editable=False, max_length=13, primary_key=True, serialize=False),
        ),
    ]
